name: restaurant_app
description: Delivero - Restaurant Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  
  # HTTP & API
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.0.0
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
  # Push Notifications  
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^17.0.0
  
  # UI Components
  cached_network_image: ^3.3.0
  fl_chart: ^0.65.0
  shimmer: ^3.0.0
  
  # Icons & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Utilities
  timeago: ^3.6.0
  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0
  geolocator: ^14.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
